package com.ops.base.education.project.security;
class SecurityConstants {
  static final String SECRET = "SecretKeyToGenJWTs"; // Ideally this key should be generated by SSL Key-Gen lib
  static final long EXPIRATION_TIME = 3600000; //  1 hour
  static final String TOKEN_PREFIX = "Student ";
  static final String HEADER_STRING = "auth";
  static final String SIGN_UP_URL = "/api/students";
  static final String LOG_IN_URL = "/v2/api/login";
}
